<?php

coworker_registered
亲爱的${coworker}，欢迎你注册成为美音婚礼联属专员。你可以随时登录美音婚礼官网 ${url} 查询你的推荐信息和业务进程。美音婚礼期待与你携手同行。

coworker_referred
亲爱的${coworker}, 我们已经记录了你的推荐，请随时登录 ${url} 查看你的推荐详情及最新进程。Tips: 与客户真诚沟通并及时回访有助于订单的达成。

coworker_success
亲爱的${coworker}，很高兴你的推荐已经达成，请登录 ${url} 查看，此订单的佣金 ${amount} 元将很快转入你指定的账户。美音婚礼一路与你同行，感谢有你。

coworker_advanced_referred
亲爱的${coworker}, 你的隶属专员有新的推荐，请登录 ${url} 查看推荐详情及最新进程。Tips: 与你的隶属专员一起工作并交流服务客户的方法和技巧，真诚对待客户有助于订单的达成。

coworker_advanced_success
亲爱的${coworker}，很高兴你的隶属专员的推荐已经达成，请登录 ${url} 查看，此订单的联属佣金 ${amount} 元将很快转入你指定的账户。美音婚礼一路与你同行，感谢有你。

service_enquiry
亲爱的${groom_name}&${bride_name}，感谢垂询美音婚礼全程精致婚礼服务。有任何问题请随时联系我们，座机 ${landline} ，手机 ${mobile} ，美音婚礼官网 ${url}

service_confirmed
亲爱的${groom_name}&${bride_name}，感谢选择美音婚礼提供的全程精致婚礼服务，感谢托付与信任。请查看婚礼筹备日程安排 ${info_url} 以做参考。美音婚礼座机 ${landline} ，手机 ${mobile} ，官网 ${url}

service_finished
亲爱的${groom_name}&${bride_name}，美音婚礼诚祝你们此心永恒，爱情绵长，感谢选择美音婚礼。有空请来坐，随时恭候。

customer_reminder
亲爱的${groom_name}&${bride_name}，距你们的婚期还有${day_counter}天，请记得访问 ${url} ，点击"编辑"填写婚礼相关联系人信息。Tips: "授权码"为你的手机号码，婚礼前一天美音婚礼会将此页面发送给所有相关人，确保婚礼全程沟通无虞。另，请查看婚礼前需确认物品清单 ${list_url} 并转发各相关人以便核查。

customer_wedding_contact
亲爱的${name}，您是${groom_name}&${bride_name}明日大婚的相关人，请访问 ${url} 查看婚礼及相关联系人详情，以确保沟通无虞。很荣幸能与您一起见证幸福时刻，感谢您的付出与支持。Tips: 浏览婚礼信息页面时，点击手机右上角浏览器菜单，选择"添加到主屏幕"，之后您可以点击手机桌面上的"美音婚礼"快速到达此婚礼信息页面。

customer_contact_confirmation
亲爱的${groom_name}&${bride_name}, 明日婚礼的信息详情 ${url} 已发送给所有相关人，请查看。如有变动请点击"编辑"更改，即时生效，以确保各相关人沟通无碍。Tips: 浏览婚礼信息页面时，点击手机右上角浏览器菜单，选择"添加到主屏幕"，之后您可以点击手机桌面上的"美音婚礼"快速到达此婚礼信息页面。

customer_contact_bye
亲爱的${name}，${groom_name}&${bride_name}的婚礼已圆满举行，感谢有您，美音婚礼期待与您再次相遇，分享浪漫幸福时光。美音婚礼官网 ${url}

coworker_inform
亲爱的${coworker}，你的客户已经联系美音婚礼咨询婚礼事宜，推荐状态已更新，请登录 ${url} 查看。Tips: 在适宜的时间询问客户有关筹备进程并提供帮助，有助于与客户建立信任关系。

coworker_advanced_inform
亲爱的${coworker}，你的隶属专员推荐客户已经联系美音婚礼咨询婚礼事宜，推荐状态已更新，请登录 ${url} 查看。Tips: 与你的隶属专员共同面对客户并主动提供帮助，有助于与客户建立良好的信任关系。