<?php
/**
 * Implements hook_views_api().
 */
function myviews_views_api() {
  return array(
    'api' => '3.0',
  );
}

/**
 * Implements hook_views_default_views().
 */
function myviews_views_default_views() {
  $path = './' . drupal_get_path('module', 'myviews') . '/views/*.inc';
  $views = array();
  foreach (glob($path) as $views_filename) {
  	require_once($views_filename);
  }
  return $views;
}
